In [ ]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [31]:
from __future__ import print_function
import torch
import numpy as np

Construct a 5x3 matrix, uninitialized:



In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00, -4.6566e-10, -1.8012e+16],
        [ 3.6902e+19,  1.1210e-44,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  8.2181e+20,  1.6784e-07],
        [ 5.3193e+22,  2.1770e+23,  5.3134e-08]])


Construct a randomly initialized matrix:



In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8554, 0.0872, 0.9694],
        [0.9798, 0.1740, 0.0496],
        [0.1727, 0.0631, 0.3591],
        [0.2654, 0.2621, 0.7367],
        [0.3879, 0.3199, 0.8576]])


Construct a matrix filled zeros and of dtype long:



In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [14]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.0091,  0.3246, -0.5517],
        [ 0.3487, -0.1344,  1.4343],
        [ 1.0750,  0.1643, -0.5207],
        [-0.7447, -0.0145,  1.5939],
        [-0.0357, -2.0002,  1.0226]])


Get its size:



In [15]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [16]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.9600,  0.9891,  0.2277],
        [ 0.7872,  0.0700,  2.2306],
        [ 1.6411,  1.1194,  0.1307],
        [-0.0457,  0.5215,  1.6461],
        [ 0.8129, -1.6776,  1.2579]])


Addition: syntax 2



In [17]:
print(torch.add(x, y))

tensor([[-0.9600,  0.9891,  0.2277],
        [ 0.7872,  0.0700,  2.2306],
        [ 1.6411,  1.1194,  0.1307],
        [-0.0457,  0.5215,  1.6461],
        [ 0.8129, -1.6776,  1.2579]])


Addition: providing an output tensor as argument



In [18]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.9600,  0.9891,  0.2277],
        [ 0.7872,  0.0700,  2.2306],
        [ 1.6411,  1.1194,  0.1307],
        [-0.0457,  0.5215,  1.6461],
        [ 0.8129, -1.6776,  1.2579]])


Addition: in-place



In [21]:
# adds x to y
y.add_(x)
print(y)

tensor([[-2.9781,  1.6383, -0.8757],
        [ 1.4847, -0.1988,  5.0992],
        [ 3.7910,  1.4480, -0.9107],
        [-1.5350,  0.4925,  4.8340],
        [ 0.7414, -5.6780,  3.3032]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [22]:
print(x[:, 1])

tensor([ 0.3246, -0.1344,  0.1643, -0.0145, -2.0002])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [23]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [24]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.2540])
-0.2539561092853546


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [37]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [38]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [39]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [41]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [40]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!